<?php


namespace Kodilab\Deployer\Tests\Unit\Git\Diff\Entries;


use Kodilab\Deployer\Exceptions\DiffEntryIncoherenceException;
use Kodilab\Deployer\Git\Diff\Entries\Add;
use Kodilab\Deployer\Git\Diff\Entries\EntryCollection;
use Kodilab\Deployer\Git\Diff\Entries\Modify;
use Kodilab\Deployer\Tests\TestCase;

class EntryCollectionTest extends TestCase
{
    /**
     * @var EntryCollection
     */
    protected $collection;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->collection = new EntryCollection();
    }

    public function test_add_entry_should_throw_an_exception_if_already_an_entry_exists_with_the_same_source()
    {
        $this->expectException(DiffEntryIncoherenceException::class);

        $entry = new Add($this->faker->name);
        $entry2 = new Modify($entry->getSource());

        $this->collection->add($entry);
        $this->collection->add($entry2);
    }
}
