<?php


namespace Kodilab\Deployer\Tests\Unit\Git\Diff\Entries;


use Kodilab\Deployer\Changes\Add;
use Kodilab\Deployer\Changes\ChangeList;
use Kodilab\Deployer\Changes\Modify;
use Kodilab\Deployer\Configuration\Configuration;
use Kodilab\Deployer\Exceptions\ChangeIncoherenceException;
use Kodilab\Deployer\Tests\TestCase;

class ChangeListTest extends TestCase
{
    /**
     * @var ChangeList
     */
    protected $collection;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->collection = new ChangeList(new Configuration(require __DIR__ .'/../../../config/config.php'));
    }

    public function test_add_entry_should_throw_an_exception_if_already_an_entry_exists_with_the_same_source()
    {
        $this->expectException(ChangeIncoherenceException::class);

        $entry = new Add($this->faker->name);
        $entry2 = new Modify($entry->getSource());

        $this->collection->add($entry);
        $this->collection->add($entry2);
    }
}
