<?php


namespace Kodilab\Deployer\Tests\Unit\Composer;


use Kodilab\Deployer\ComposerLock\Dependency;
use Kodilab\Deployer\ComposerLock\DependencyCollection;
use Kodilab\Deployer\Exceptions\InvalidComposerLockFileException;
use Kodilab\Deployer\Tests\TestCase;

class DependencyCollectionTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_dependencyCollection_should_contain_a_collection_of_dependencies()
    {
        $collection = new DependencyCollection();
        $collection->put(0, new Dependency($this->loadMockComposerLock()['packages'][0]));

        $this->assertEquals([
            0 => (new Dependency($this->loadMockComposerLock()['packages'][0]))->toArray()
        ], $collection->toArray());
    }
}
