<?php


namespace Kodilab\Deployer\Tests\Unit\Composer;


use Kodilab\Deployer\ComposerLock\ComposerLock;
use Kodilab\Deployer\ComposerLock\Parser;
use Kodilab\Deployer\Tests\TestCase;

class ParserTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_parse_should_return_a_composerLock_instance()
    {
        $this->assertEquals(ComposerLock::class, get_class(Parser::parse("")));
    }
}
