<?php


namespace Kodilab\Deployer\Git\Diff\Entries;


use Kodilab\Deployer\Exceptions\DiffEntryIncoherenceException;
use Kodilab\Deployer\Support\Collection;

class EntryCollection extends Collection
{

    /**
     * @param Entry $item
     * @return Collection
     * @throws DiffEntryIncoherenceException
     */
    public function add($item)
    {
        $this->validateEntryCoherence($item);
        return parent::add($item);
    }

    /**
     * @param mixed $key
     * @param Entry $value
     * @return Collection
     * @throws DiffEntryIncoherenceException
     */
    public function put($key, $value)
    {
        $this->validateEntryCoherence($value);
        return parent::put($key, $value); // TODO: Change the autogenerated stub
    }

    /**
     * @param Entry $entry
     * @throws DiffEntryIncoherenceException
     */
    protected function validateEntryCoherence(Entry $entry)
    {
        /** @var Entry $item */
        foreach ($this->items as $item)
        {
            if ($item->hasSameSource($entry)) {
                throw new DiffEntryIncoherenceException($item, $entry);
            }
        }
    }
}
